variable "name" {
  description = "Name prefix, e.g. jobproc-dev."
  type        = string
}

variable "vpc_id" {
  description = "VPC to create the database security group in."
  type        = string
}

variable "subnet_ids" {
  description = "Private subnet IDs for the DB subnet group (at least 2 AZs)."
  type        = list(string)

  validation {
    condition     = length(var.subnet_ids) >= 2
    error_message = "RDS subnet groups need subnets in at least 2 AZs."
  }
}

variable "allowed_security_group_ids" {
  description = "Security groups allowed to connect on 5432, keyed by a static label (e.g. { app = sg-..., worker = sg-... })."
  type        = map(string)
  default     = {}
}

variable "engine_version" {
  description = "PostgreSQL major version. RDS picks the latest minor version."
  type        = string
  default     = "16"
}

variable "instance_class" {
  description = "RDS instance class."
  type        = string
  default     = "db.t3.micro"
}

variable "allocated_storage" {
  description = "Storage in GiB (20 is the gp3 minimum)."
  type        = number
  default     = 20
}

variable "db_name" {
  description = "Name of the initial database."
  type        = string
  default     = "jobs"
}

variable "username" {
  description = "Master username (password is generated by RDS)."
  type        = string
  default     = "jobproc"
}
